In [7]:
import png
import numpy as np

In [ ]:
# save data
import pickle
pickle_obj = {"pix_arr": pix_arr}
pickle.dump(pickle_obj, open('pix_arr.pkl', 'wb'))

In [2]:
# load data
import pickle
pickle_obj = pickle.load(open('pix_arr.pkl', 'rb'))
pix_arr = pickle_obj.get('pix_arr')

In [13]:
pix_arr

array([[[   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ]],

       [[   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ],
        [   0.        ,    0.        ,    0.        ]],

      

In [3]:
# works
pix_arr_8 = pix_arr.astype('uint8')
png.from_array(pix_arr_8, mode="RGB").save("pix8.png")

In [17]:
pix_arr_8

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [166, 174,  27],
        [126, 184,  38],
        [175, 115,  93],
        [ 78,  31,  23],
        [129,  46,  21],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [229,  30,  32],
        [ 51, 103,  23],
        [213, 205,  27],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0

In [5]:
def decode(file):
    r = png.Reader(file)
    result = r.read_flat()
    result_arr = result[2]
    result_list = list(result_arr)
    return result, result_arr, result_list

In [ ]:
def encode():
    

In [8]:
c = np.random.rand(3,9)
c = c*2000

In [11]:
c

array([[1288.6728813 , 1449.20358847, 1272.05766705,  190.46538626,
         811.91151229,  573.72032582, 1415.94436013,  505.15679021,
         612.45996601],
       [1263.04924103, 1914.16274432, 1832.33719518, 1965.57349491,
         154.66330896,  628.87547318,  610.19387455,  424.46954601,
        1629.80880675],
       [1685.2347507 ,  838.37241038,  386.84068804,  485.38287583,
        1796.48956596, 1411.47432812,  535.81497352,  797.91842242,
        1890.34507007]])

In [12]:
c8

array([[  8, 169, 248, 190,  43,  61, 135, 249, 100],
       [239, 122,  40, 173, 154, 116,  98, 168,  93],
       [149,  70, 130, 229,   4, 131,  23,  29,  98]], dtype=uint8)

In [9]:
# has color, but only 256
c8 = c.astype('uint8')
png.from_array(c8, mode="RGB").save("foo8.png")

In [10]:
r, r_a, r_l = decode("foo8.png")
r

(3,
 3,
 array('B', [8, 169, 248, 190, 43, 61, 135, 249, 100, 239, 122, 40, 173, 154, 116, 98, 168, 93, 149, 70, 130, 229, 4, 131, 23, 29, 98]),
 {'greyscale': False,
  'alpha': False,
  'planes': 3,
  'bitdepth': 8,
  'interlace': 0,
  'size': (3, 3)})

In [ ]:

pix_arr_16 = pix_arr.astype('uint16')
png.from_array(pix_arr_16, mode="L")
png.from_array(pix_arr_16, mode="L").save("foo.png")



# Try to decode and encode given png files
r=png.Reader("trainA/02_000000000975.png")
r.read_flat()

# {'greyscale': False, 'alpha': False, 'planes': 3, 'bitdepth': 8, 'interlace': 0, 'size': (768, 256)}

flower_list = decode("trainA/02_000000000975.png")
flower_arr = np.array(flower_list)
f8 = flower_arr.astype('uint8')

f8_2d = np.reshape(f8, (768, 256, 3))

png.from_array(f8_2d, mode="RGB").save("flower8.png")




decode("foo8.png")



image_2d = np.vstack(map(np.uint16, r))

png.from_array(c8, mode="RGB").save("foo8.png")
png.from_array(c8, mode="L").save("foo8L.png")


info = {"height":3, "width":3, "bitdepth":8}
png.from_array(c16, mode="RGB", info=info).save("foo8h3w3b8.png")

# no
info = {"height":3, "width":3, "bitdepth":16}
png.from_array(c16, mode="RGB", info=info).save("foo8h3w3b16.png")

png.from_array(c16, mode="L").save("foo16L.png")


c16 = c.astype('uint16')
png.from_array(c16, mode="RGB").save("foo16.png")

info = {"height":3, "width":3, "bitdepth":8}
png.from_array(c16, mode="RGB", info=info).save("foo16h3w3b8.png")

# no
info = {"height":3, "width":3, "bitdepth":16}
png.from_array(c16, mode="RGB;16", info=info).save("foo16h3w3b16.png")



In [24]:
# solution source: https://stackoverflow.com/questions/25696615/can-i-save-a-numpy-array-as-a-16-bit-image-using-normal-enthought-python

import png

import numpy as np

# The following import is just for creating an interesting array
# of data.  It is not necessary for writing a PNG file with PyPNG.
from scipy.ndimage import gaussian_filter


# Make an image in a numpy array for this demonstration.
nrows = 240
ncols = 320
np.random.seed(12345)
x = np.random.randn(nrows, ncols, 3)
print("x[0][0]:", x[0][0])
print("x:", x.shape)

# y is our floating point demonstration data.
y = gaussian_filter(x, (16, 16, 0))
print("y[0][0]:", y[0][0])
print("y:", y.shape)

# Convert y to 16 bit unsigned integers.
z = (65535*((y - y.min())/y.ptp())).astype(np.uint16)
print("z[0][0]:", z[0][0])
print("z:", z.shape)

# Use pypng to write z as a color PNG.
with open('foo_color.png', 'wb') as f:
    writer = png.Writer(width=z.shape[1], height=z.shape[0], bitdepth=16)
    # Convert z to the Python list of lists expected by
    # the png writer.
    z2list = z.reshape(-1, z.shape[1]*z.shape[2]).tolist()
    writer.write(f, z2list)

# Here's a grayscale example.
zgray = z[:, :, 0]

# Use pypng to write zgray as a grayscale PNG.
with open('foo_gray.png', 'wb') as f:
    writer = png.Writer(width=z.shape[1], height=z.shape[0], bitdepth=16, greyscale=True)
    zgray2list = zgray.tolist()
    writer.write(f, zgray2list)

x[0][0]: [-0.20470766  0.47894334 -0.51943872]
x: (240, 320, 3)
y[0][0]: [-0.02198602 -0.01280045  0.00765323]
y: (240, 320, 3)
z[0][0]: [13521 18078 28224]
z: (240, 320, 3)


ProtocolError: ProtocolError: Expected 320 values but got 960 value, in row 0

In [28]:
import numpy as np
import numpngw

# The following import is just for creating an interesting array
# of data.  It is not necessary for writing a PNG file with PyPNG.
from scipy.ndimage import gaussian_filter


# Make an image in a numpy array for this demonstration.
nrows = 240
ncols = 320
np.random.seed(12345)
x = np.random.randn(nrows, ncols, 3)
print("x[0][0]:", x[0][0])
print("x:", x.shape)

# y is our floating point demonstration data.
y = gaussian_filter(x, (16, 16, 0))
print("y[0][0]:", y[0][0])
print("y:", y.shape)

# Convert y to 16 bit unsigned integers.
z = (65535*((y - y.min())/y.ptp())).astype(np.uint16)
print("z[0][0]:", z[0][0])
print("z:", z.shape)

# Use numpngw to write z as a color PNG.
numpngw.write_png('foo_color.png', z)

# Here's a grayscale example.
zgray = z[:, :, 0]

# Use numpngw to write zgray as a grayscale PNG.
numpngw.write_png('foo_gray.png', zgray)

x[0][0]: [-0.20470766  0.47894334 -0.51943872]
x: (240, 320, 3)
y[0][0]: [-0.02198602 -0.01280045  0.00765323]
y: (240, 320, 3)
z[0][0]: [13521 18078 28224]
z: (240, 320, 3)


In [27]:
z_r = numpngw.read_png('foo_color.png')

AttributeError: module 'numpngw' has no attribute 'read_png'

In [29]:
r, r_a, r_l = decode("foo_color.png")
r

(320,
 240,
 array('H', [13521, 18078, 28224, 13551, 18097, 28167, 13610, 18136, 28056, 13697, 18197, 27886, 13811, 18276, 27666, 13953, 18377, 27395, 14125, 18501, 27076, 14320, 18648, 26711, 14542, 18817, 26304, 14789, 19011, 25861, 15061, 19229, 25387, 15357, 19474, 24885, 15673, 19745, 24358, 16012, 20041, 23812, 16370, 20367, 23252, 16748, 20718, 22680, 17144, 21099, 22105, 17555, 21506, 21525, 17982, 21940, 20948, 18424, 22400, 20376, 18879, 22883, 19812, 19346, 23392, 19258, 19824, 23921, 18715, 20307, 24469, 18187, 20798, 25032, 17674, 21291, 25610, 17180, 21788, 26198, 16703, 22283, 26790, 16246, 22777, 27384, 15807, 23264, 27975, 15390, 23744, 28557, 14995, 24214, 29128, 14620, 24670, 29680, 14268, 25108, 30207, 13937, 25528, 30707, 13629, 25926, 31174, 13343, 26297, 31601, 13081, 26638, 31984, 12840, 26950, 32319, 12623, 27224, 32605, 12430, 27461, 32833, 12258, 27658, 33005, 12111, 27813, 33115, 11988, 27925, 33162, 11888, 27992, 33146, 11814, 28015, 33065, 11761, 27989, 32